### ISSUE TITLE
The java example fails

### ISSUE THREAD

**Issue by kirbyfan64** [felix-lang/fbuild#10]
```
javac                    : World.java -> RegularFileObject[build/world/World.class]
Traceback (most recent call last):
  File "../../fbuild-light", line 13, in <module>
    exec(compile(f.read(), fbuild_exename, 'exec'))
  File "../../bin/fbuild", line 159, in <module>
    sys.exit(main())
  File "../../bin/fbuild", line 135, in main
    result = build(ctx)
  File "../../bin/fbuild", line 82, in build
    target.function(ctx)
  File "/media/ryan/stuff/fb2/examples/java/fbuildroot.py", line 6, in build
    lib = java.build_lib('lib.jar', ['World.java'])
  File "../../lib/fbuild/builders/java.py", line 296, in build_lib
    return self.link_lib(dst, objs, cwd=cwd, **lkwargs)
  File "../../lib/fbuild/builders/java.py", line 272, in link_lib
    return self.jar.create(*args, **kwargs)
  File "../../lib/fbuild/db/__init__.py", line 162, in __call__
    result, srcs, dsts = self.call(*args, **kwargs)
  File "../../lib/fbuild/db/__init__.py", line 166, in call
    return self.method.__self__.ctx.db.call(self.method, *args, **kwargs)
  File "../../lib/fbuild/db/database.py", line 100, in call
    dsts)
  File "../../lib/fbuild/rpc.py", line 68, in call
    raise result.result
  File "../../lib/fbuild/rpc.py", line 112, in _process
    result.result = self._handler(*args, **kwargs)
  File "../../lib/fbuild/db/database.py", line 24, in handle_rpc
    return method(*args, **kwargs)
  File "../../lib/fbuild/db/backend.py", line 42, in prepare
    call_file_digests = self.check_call_files(call_id, srcs)
  File "../../lib/fbuild/db/backend.py", line 143, in check_call_files
    d, file_id, file_digest = self.check_call_file(call_id, file_name)
  File "../../lib/fbuild/db/backend.py", line 165, in check_call_file
    dirty, file_id, mtime, digest = self.add_file(file_name)
  File "../../lib/fbuild/db/backend.py", line 249, in add_file
    file_mtime = file_path.getmtime()
  File "../../lib/fbuild/path.py", line 224, in getmtime
    return os.path.getmtime(self)
  File "/media/stuff/anaconda/lib/python3.4/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: Path('RegularFileObject[build/world/World.class]')
```

**Comment by kirbyfan64** [comment]
Scratch that, the builder is pretty much broken.
