### ISSUE TITLE
Null character error running on windows

### ISSUE THREAD

**Issue by spacehamster** [felix-lang/fbuild#35]
When I try to run the cxx build file in the examples, I get the following error:
```
determining platform     : {'win32', 'windows'}
looking for cl.exe       : ok C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\cl.exe
checking cl.exe          : Traceback (most recent call last):
  File "C:\Python36\Scripts\fbuild-script.py", line 11, in <module>
    load_entry_point('fbuild==0.2', 'console_scripts', 'fbuild')()
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\main.py", line 193, in main
    result = build(ctx)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\main.py", line 131, in build
    target.function(ctx)
  File "C:\Users\Tom\Dropbox\Code\FrameworkTests\BuildSystems\fbuild\cpp\fbuildroot.py", line 6, in build
    ({'posix'}, {'flags': ['-Wall', '-Werror']}),
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\__init__.py", line 438, in __call__
    **new_kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\functools.py", line 64, in call
    return import_function(function)(*args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 180, in __call__
    result, srcs, dsts = self.call(*args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 185, in call
    return ctx.db.call(self.function, ctx, *args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\database.py", line 184, in call
    call_result = outer_function(*args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\cxx\msvc.py", line 8, in static
    return fbuild.builders.c.msvc.static(*args, src_suffix=src_suffix, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 531, in static
    compiler=Compiler(ctx, Cl(ctx, **kwargs),
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 124, in __call__
    *args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\database.py", line 184, in call
    call_result = outer_function(*args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 119, in __call_super__
    return super().__call__(*args, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 38, in __init__
    if not self.check_flags(flags):
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 116, in check_flags
    self([src], flags=flags, quieter=1, cwd=src.parent)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 103, in __call__
    return self.ctx.execute(cmd, msg2=msg2, **kwargs)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\context.py", line 202, in execute
    **kwargs)
  File "C:\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\subprocess\killableprocess.py", line 168, in _execute_child
    winprocess.EnvironmentBlock(env),
  File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\subprocess\winprocess.py", line 129, in __init__
    self._as_parameter_ = LPCWSTR("\0".join(values))
ValueError: embedded null character
```

**Comment by skaller** [comment]
> On 10 Jun. 2018, at 20:01, spacehamster <notifications@github.com> wrote:
> 
> When I try to run the cxx build file in the examples, I get the following error:

Hopefully Ryan can sort that out…

> 
> determining platform     : {'win32', 'windows'}
> looking for cl.exe       : ok C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\cl.exe
> checking cl.exe          : Traceback (most recent call last):
>   File "C:\Python36\Scripts\fbuild-script.py", line 11, in <module>
>     load_entry_point('fbuild==0.2', 'console_scripts', 'fbuild')()
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\main.py", line 193, in main
>     result = build(ctx)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\main.py", line 131, in build
>     target.function(ctx)
>   File "C:\Users\Tom\Dropbox\Code\FrameworkTests\BuildSystems\fbuild\cpp\fbuildroot.py", line 6, in build
>     ({'posix'}, {'flags': ['-Wall', '-Werror']}),
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\__init__.py", line 438, in __call__
>     **new_kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\functools.py", line 64, in call
>     return import_function(function)(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 180, in __call__
>     result, srcs, dsts = self.call(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 185, in call
>     return ctx.db.call(self.function, ctx, *args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\database.py", line 184, in call
>     call_result = outer_function(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\cxx\msvc.py", line 8, in static
>     return fbuild.builders.c.msvc.static(*args, src_suffix=src_suffix, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 531, in static
>     compiler=Compiler(ctx, Cl(ctx, **kwargs),
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 124, in __call__
>     *args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\database.py", line 184, in call
>     call_result = outer_function(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\db\__init__.py", line 119, in __call_super__
>     return super().__call__(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 38, in __init__
>     if not self.check_flags(flags):
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 116, in check_flags
>     self([src], flags=flags, quieter=1, cwd=src.parent)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\builders\c\msvc.py", line 103, in __call__
>     return self.ctx.execute(cmd, msg2=msg2, **kwargs)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\context.py", line 202, in execute
>     **kwargs)
>   File "C:\Python36\lib\subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\subprocess\killableprocess.py", line 168, in _execute_child
>     winprocess.EnvironmentBlock(env),
>   File "C:\Python36\lib\site-packages\fbuild-0.2-py3.6.egg\fbuild\subprocess\winprocess.py", line 129, in __init__
>     self._as_parameter_ = LPCWSTR("\0".join(values))
> ValueError: embedded null character
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—
John Skaller
skaller@internode.on.net

**Comment by kirbyfan64** [comment]
Ah crud, I remember this... [It's a bug in CPython 3.6](https://bugs.python.org/issue32745). @spacehamster I just pushed a potential fix to the `win-null` branch. Could you try it out and see if it works?
